### ISSUE TITLE
Depending on o.g.e:schema2beans:6.7 causes javac lint to issue warning

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish-repackaged#5]
After migration of dependency from:
```xml
            <dependency>
                <groupId>org.glassfish.main.extras</groupId>
                <artifactId>glassfish-embedded-all</artifactId>
                <version>5.0</version>
            </dependency>
```
to
```xml
            <dependency>
                <groupId>org.glassfish.main.extras</groupId>
                <artifactId>glassfish-embedded-all</artifactId>
                <version>5.1.0</version>
            </dependency>
```
`javac` started to issue lint warning:
```
[WARNING] Supported source version 'RELEASE_7' from annotation processor 'org.netbeans.modules.schema2beansdev.Schema2BeansProcessor' less than -source '1.8'
```
(My project does not depend on `schema2beans` (repackaged or not) directly but only on `glassfish-embedded-all`.)

With `-Werror` turned on build obviously fails.

I think it is related to change of
    `org.glassfish.external`:`schema2beans-repackaged`:`3.1.1` ([in GF5.0](https://github.com/javaee/glassfish/blob/82a839ef51e3138d038b1c2b635bdaaf1d4407e2/appserver/pom.xml#L116))
to
    `org.glassfish.external`:`schema2beans`:`6.7` ([GF5.1](https://github.com/eclipse-ee4j/glassfish/blob/c6ef9edc13cfa21c5cc488967309d9e6f37927dc/appserver/pom.xml#L91)),
(while version of `org.netbeans.api`:`org-netbeans-modules-schema2beans` migrated from `RELEASE55` to `RELEASE82`).

[Example of failed build](https://travis-ci.org/pzrep/schema2beans-lint-processor/builds/487421453) with that change (3.1.1 -> 6.7).

---

Raising here per https://github.com/eclipse-ee4j/glassfish-repackaged/blob/eab519ce86c9649f303c20fa7e996c158947f30d/schema2beans/pom.xml#L67-L70.

**Comment by pzygielo** [comment]
[travis:487433553](https://travis-ci.org/pzrep/schema2beans-lint-processor/builds/487433553) shows that using original (upstream) NB artifacts has the same effect.

**Comment by pzygielo** [comment]
If one does not need annotation processing - turning it off (`-proc:none`) prevents this warning.
It works for me.
I am sorry for noise. ;)

**Comment by arjantijms** [comment]
@pzygielo the upstream version of this artefact has now finally been updated:

https://github.com/apache/netbeans/commit/467f689b3231cd60d47115daaaa9f6340550377d#diff-1f00860b4de111dad0e2fc7aaa9de6a58f39d2486582f8653c3078f8db18cdab

**Comment by pzygielo** [comment]
Thanks for checking and for the update.
Indeed, since RELEASE113 it no longer complains.
By any chance, do you know if
https://github.com/eclipse-ee4j/glassfish-repackaged/blob/a9b62577f13f6865873572b94675f3109a9e52c1/schema2beans/pom.xml#L36
is considered for the update and propagation to the main GF?

**Comment by arjantijms** [comment]
If you want it to be updated and propagated to GF, let me know ;) I'd say let's try updating it to the latest release, test if everything still works, and if so include it.

**Comment by pzygielo** [comment]
For me, such update is not necessary.
I see no other issue reported for that, so probably it's not worth the effort today.
